# Generated by Django 2.2.3 on 2020-08-24 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='昵称')),
            ],
            options={
                'verbose_name': '动物成员',
                'verbose_name_plural': '动物成员',
                'db_table': 'db_animal',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('financeType', models.CharField(choices=[('income', '收入'), ('outcome', '支出')], max_length=20, verbose_name='收入/支出')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('comment', models.CharField(default='', max_length=20, verbose_name='备注')),
            ],
            options={
                'verbose_name': '财务记录',
                'verbose_name_plural': '财务记录',
                'db_table': 'db_details',
            },
        ),
        migrations.CreateModel(
            name='IncomeStatistic',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('year', models.IntegerField(default=0, verbose_name='年份')),
                ('month', models.IntegerField(default=0, verbose_name='月份')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更改日期')),
                ('incomeFinance', models.FloatField(default=0, verbose_name='理财')),
                ('incomeSalary', models.FloatField(default=0, verbose_name='工资')),
                ('incomeReward', models.FloatField(default=0, verbose_name='奖金')),
                ('incomeOther', models.CharField(default='', max_length=200, verbose_name='额外收入')),
            ],
            options={
                'verbose_name': '财务统计(收入)',
                'verbose_name_plural': '财务统计(收入)',
                'db_table': 'db_statistic_income',
            },
        ),
        migrations.CreateModel(
            name='OutcomeStatistic',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('year', models.IntegerField(default=0, verbose_name='年份')),
                ('month', models.IntegerField(default=0, verbose_name='月份')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更改日期')),
                ('outcomePerMeal', models.FloatField(default=0, verbose_name='独自用餐')),
                ('outcomeTogMeal', models.FloatField(default=0, verbose_name='共同用餐')),
                ('outcomeGame', models.FloatField(default=0, verbose_name='游戏')),
                ('outcomeFamTravel', models.FloatField(default=0, verbose_name='旅游')),
                ('outcomePurchase', models.FloatField(default=0, verbose_name='购物')),
                ('outcomeTraffic', models.FloatField(default=0, verbose_name='交通')),
                ('outcomeFamCat', models.FloatField(default=0, verbose_name='趣多多')),
                ('outcomeFamEle', models.FloatField(default=0, verbose_name='水电')),
                ('outcomeFamGas', models.FloatField(default=0, verbose_name='煤气')),
                ('outcomeFamPurchase', models.FloatField(default=0, verbose_name='家庭采购')),
                ('outcomeOther', models.CharField(default='', max_length=200, verbose_name='额外支出')),
            ],
            options={
                'verbose_name': '财务统计(支出)',
                'verbose_name_plural': '财务统计(支出)',
                'db_table': 'db_statistic_outcome',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更改日期')),
                ('catIncome', models.FloatField(verbose_name='猫收入')),
                ('catOutcome', models.FloatField(verbose_name='猫支出')),
                ('mouseIncome', models.FloatField(verbose_name='鼠收入')),
                ('mouseOutcome', models.FloatField(verbose_name='鼠支出')),
                ('specialIncome', models.CharField(default='', max_length=500, verbose_name='共同收入')),
                ('specialOutcome', models.CharField(default='', max_length=500, verbose_name='共同支出')),
            ],
            options={
                'verbose_name': '财务小结',
                'verbose_name_plural': '财务小结',
                'db_table': 'db_summary',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('financeType', models.CharField(choices=[('income', '收入'), ('outcome', '支出')], max_length=20, verbose_name='收入/支出')),
                ('foodType', models.CharField(default='', max_length=500, unique=True, verbose_name='类型')),
            ],
            options={
                'verbose_name': '食物种类',
                'verbose_name_plural': '食物种类',
                'db_table': 'db_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('userid', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'db_table': 'db_user',
            },
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_period'),
        ),
        migrations.AddField(
            model_name='outcomestatistic',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='支出统计', to='finance.Animal', to_field='name', verbose_name='成员2'),
        ),
        migrations.AddField(
            model_name='incomestatistic',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='收入统计', to='finance.Animal', to_field='name', verbose_name='成员3'),
        ),
        migrations.AddField(
            model_name='detail',
            name='foodType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='finance.Type', to_field='foodType', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='detail',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='具体记录', to='finance.Animal', to_field='name', verbose_name='成员1'),
        ),
    ]
