# Generated by Django 2.2.3 on 2020-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomestatistic',
            name='familyExpense',
            field=models.FloatField(default=0, verbose_name='月度家庭支出'),
        ),
        migrations.AddField(
            model_name='outcomestatistic',
            name='personalExpense',
            field=models.FloatField(default=0, verbose_name='月度个人支出'),
        ),
    ]
