# Generated by Django 2.2.3 on 2020-03-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200311_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='financeType',
        ),
        migrations.AddField(
            model_name='summary',
            name='catIncome',
            field=models.FloatField(default='1', verbose_name='猫收入'),
        ),
        migrations.AddField(
            model_name='summary',
            name='catOutcome',
            field=models.FloatField(default='1', verbose_name='猫支出'),
        ),
        migrations.AddField(
            model_name='summary',
            name='mouseIncome',
            field=models.FloatField(default='1', verbose_name='鼠收入'),
        ),
        migrations.AddField(
            model_name='summary',
            name='mouseOutcome',
            field=models.FloatField(default='1', verbose_name='鼠支出'),
        ),
        migrations.AddField(
            model_name='summary',
            name='remainFood',
            field=models.CharField(default='1', max_length=500, verbose_name='额外支出'),
        ),
        migrations.AddField(
            model_name='summary',
            name='specialIncome',
            field=models.CharField(default='1', max_length=500, verbose_name='额外收入'),
        ),
        migrations.AddField(
            model_name='summary',
            name='specialOutcome',
            field=models.CharField(default='1', max_length=500, verbose_name='额外支出'),
        ),
        migrations.AddField(
            model_name='summary',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更改日期'),
        ),
    ]
