# Generated by Django 2.2.3 on 2020-03-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20200311_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='member',
        ),
    ]
