# Generated by Django 2.2.3 on 2020-03-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_summary_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Animal', to_field='name', verbose_name='成员'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='remainFood',
            field=models.CharField(default='', max_length=500, verbose_name='额外支出'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='specialIncome',
            field=models.CharField(default='', max_length=500, verbose_name='额外收入'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='specialOutcome',
            field=models.CharField(default='', max_length=500, verbose_name='额外支出'),
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_period'),
        ),
    ]
