# Generated by Django 2.2.3 on 2020-03-12 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20200312_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Animal', to_field='name', verbose_name='成员'),
        ),
    ]
